require 'spree_core'
require 'spree_dashboard/engine'
require 'spree/data_visualisations/data_visualisation.rb'
require 'spree/data_visualisations/bar_graph_visualisation.rb'
require 'spree/data_visualisations/discrete_bar_chart_visualisation.rb'
require 'spree/data_visualisations/horizontal_bar_graph_visualisation.rb'
require 'spree/data_visualisations/line_bar_graph_visualisation.rb'
require 'spree/data_visualisations/pie_chart_visualisation.rb'
require 'spree/data_visualisations/top_taxonomies_visualisation.rb'
require 'spree/data_visualisations/total_visualisation.rb'
require 'spree/data_visualisations/completed_transactions_visualisation.rb'
require 'spree/data_visualisations/abandonments_data_visualisation.rb'
require 'spree/data_visualisations/growth_visualisation.rb'
require 'spree/data_visualisations/historical_bar_graph_visualisation.rb'

